### ISSUE TITLE
Proposal: support packages whitelist on self-host mode

### ISSUE THREAD

**Issue by Justinidlerz** [ije/esm.sh#465]
Since supporting the `private token` for npm, It's great for internal front-end projects but cannot use for business coz the server will make all our private packages public via this server.

I'm thinking can provide a whitelist/blacklist configuration to block some private packages read via this server. See like:

package-config.yaml
```yaml
whitelist:
  - @namespace/private-package-but-can-be-public-read
// Or  
blacklist:
 - @namespace/private-package-internal-only
```

Wanted to get your thoughts on this first before doing a PR if there's interest.
